### ISSUE TITLE
景嘉微显卡：wps新建文档保存时，打开文件管理器授权后应用闪退

### ISSUE THREAD

**Issue by joe1111111** [openfde/openfde#93] opened 2024-08-09 06:34 UTC
![Screenshot_20240809-143346_WPS_Office](https://github.com/user-attachments/assets/d68f094b-6896-4714-b71b-1d5a22923a63)

**Comment by warlice** [comment] 2024-08-12 09:18
caused by not updating by accident. fixed by updating mediaprovider

**Closed by warlice** 2024-08-12 09:18 UTC
